common:
   secret: secret
   config: config
   namespace: circus
   host: arch.homework

authEndpoint:
   label: auth-endpoint
   replicaCount: 1
   image: gennadytiunov/circus-auth-service:v10
   env:
      appPort: _OtusApp_Port_Endpoint_Auth
      uri: _OtusApp_URI_Endpoint_Auth
   port:
      number: 1000
      name: auth-port
   service:
      name: auth-service
      type: NodePort
      port:
         number: "1000"
         protocol: TCP

identityEndpoint:
   label: identity-service
   replicaCount: 1
   image: gennadytiunov/circus-identity-service:v10
   env:
      appPort: _OtusApp_Port_Endpoint_Identity
      uri: _OtusApp_URI_Endpoint_Identity
      token: _OtusApp_Token_Identity
   port:
      number: 1100
      name: identities-port
   service:
      name: identity-service
      type: NodePort
      port:
         number: "1100"
         protocol: TCP

sessionEndpoint:
   label: session-service
   replicaCount: 1
   image: gennadytiunov/circus-session-service:v10
   env:
      appPort: _OtusApp_Port_Endpoint_Session
      uri: _OtusApp_URI_Endpoint_Session
      token: _OtusApp_Token_Session
   port:
      number: 1200
      name: sessions-port
   service:
      name: session-service
      type: NodePort
      port:
         number: "1200"
         protocol: TCP

userEndpoint:
   label: user-endpoint
   replicaCount: 1
   image: gennadytiunov/circus-user-endpoint:v10
   env:
      appPort: _OtusApp_Port_Endpoint_User
      uri: _OtusApp_URI_Endpoint_User
      token: _OtusApp_Token_User  
   port:
      number: 1300
      name: user-port
   service:
      name: user-endpoint
      type: NodePort
      port:
         number: "1300"
         protocol: TCP

timetableEndpoint:
   label: timetable-endpoint
   replicaCount: 1
   image: gennadytiunov/circus-timetable-endpoint:v10
   env:
      appPort: _OtusApp_Port_Endpoint_Timetable
      uri: _OtusApp_URI_Endpoint_Timetable
   port:
      number: 10000
      name: timetable-port
   service:
      name: timetable-endpoint
      type: NodePort
      port:
         number: "10000"
         protocol: TCP

bookingEndpoint:
   label: booking-endpoint
   replicaCount: 1
   image: gennadytiunov/circus-booking-endpoint:v10
   env:
      appPort: _OtusApp_Port_Endpoint_Booking
   port:
      number: 10100
      name: bookings-port
   service:
      name: booking-endpoint
      type: NodePort
      port:
         number: "10100"
         protocol: TCP

paymentEndpoint:
   label: payment-endpoint
   replicaCount: 1
   image: gennadytiunov/circus-payment-endpoint:v10
   env:
      appPort: _OtusApp_Port_Endpoint_Payment
   port:
      number: 10200
      name: payment-port
   service:
      name: payment-endpoint
      type: NodePort
      port:
         number: "10200"
         protocol: TCP

notificationEndpoint:
   label: notifier-endpoint
   replicaCount: 1
   image: gennadytiunov/circus-notification-endpoint:v10
   env:
      appPort: _OtusApp_Port_Endpoint_Notification
   port:
      number: 10300
      name: notifier-port
   service:
      name: notifier-endpoint
      type: NodePort
      port:
         number: "10300"
         protocol: TCP
         
bookingOrchestrator:
   name: booking-orchestrator
   image: gennadytiunov/circus-booking-orchestrator:v10
   listeners:
      bookings: "Group.Booking.BookingMessageListener"
      payments: "Group.Booking.PaymentMessageListener"

paymentProcessor:
   name: payment-processor
   image: gennadytiunov/circus-payment-listeners:v10
   listeners:
      users: "Group.Payment.UserMessageListener"
      payments: "Group.Payment.PaymentMessageListener"

notificationProcessor:
   name: notification-processor
   image: gennadytiunov/circus-notification-listeners:v10
   listeners:
      bookings: "Group.Notification.BookingNotificationListener"

kafka:
   servers: "cp-cp-kafka-headless.kafka.svc.cluster.local:9092"
   topics:
      users: "users"
      bookings: "bookings"
      payments: "payments"
      paymentsreplies: "payments-replies"
      notifications: "notifications"

db:
   label: mssqlexpress
   replicaCount: 1
   image: mcr.microsoft.com/mssql/server
   awaiterImage: busybox:1.28
   env:
      uri: _OtusApp_DB_URI
   mssql:
      acceptEula: "Y"
      edition: "Express"
   mount:
      name: mssqlexpressvolume
      path: /var/opt/mssql
      access: "ReadWriteOnce"
      class: standard
      size: 500Mi
   name: OtusLabs
   user: sa
   password: "0tuS1@b$"
   port:
      number: 1433
      name: sql-port
   service:
      name: db-service
      type: NodePort
      port:
         number: "15000"
         protocol: TCP
   msTools:
      image: mcr.microsoft.com/mssql-tools
      path: /opt/mssql-tools/bin