apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
   name: {{ .Values.webApp.label }}-ingress
   annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/auth-url: "http://{{ .Values.authService.service.name }}.{{ .Values.common.namespace }}.svc.cluster.local:{{ .Values.authService.port.number }}/auth"
      nginx.ingress.kubernetes.io/auth-signin: "http://$host/signin"
      nginx.ingress.kubernetes.io/auth-response-headers: "X-User-Id"
spec:
  rules:
  {{- with .Values.webApp }}
  - host: {{ .host }}
    http:
      paths:
      - backend:
           serviceName: {{ .service.name }}
           servicePort: {{ .service.port.number }}
        path: /profile
  {{- end }}