apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.common.namespace }}
{{- with .Values.ordersApp }}
  name: {{ .service.name }}
  
  labels:
    app: {{ .service.name }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port.number }}
      name: {{ .port.name }}
      targetPort: {{ .port.name }}
      protocol: {{ .service.port.protocol }}
  selector:
    app: {{ .label }}
{{- end }}