apiVersion: v1
kind: Secret
metadata:
   name: {{ .Values.common.secret }}
type: Opaque
data:
   DBPASSWORD: {{ .Values.db.password | b64enc | quote }}
   DBURI: {{ printf "Server=%s,%s;Initial Catalog=%s;User ID=%s;Password=%s" .Values.db.service.name .Values.db.service.port.number .Values.db.name .Values.db.user .Values.db.password | b64enc | quote }}
   {{ .Values.identityService.env.token }}: "OGNhNTE2MjQtOTI5MS00ZDcwLWFiMTctMDhhNjE3OGVhYWJm"
   {{ .Values.sessionService.env.token }}: "ZmJmZGY2MTItODQxZi00NjQzLWEyMWQtNzA5YjFiNDhjMmJl"
   {{ .Values.userService.env.token }}: "YmI0NTMxODktMjljYy00ZWE5LWE3N2QtMDNiNjExM2Y2ODMz"