apiVersion: v1
kind: ConfigMap
metadata:
   name: {{ .Values.common.config }}
data:
   {{ .Values.timetableEndpoint.env.uri }}: "http://{{ .Values.timetableEndpoint.service.name }}:{{ .Values.timetableEndpoint.service.port.number }}"