apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
   name: auth-proxy
   annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
   rules:
   - host: {{ .Values.common.host }}
{{- with .Values.authEndpoint.service }}
     http:
        paths:
        - path: /{{ .name }}/(health)
          backend:
             serviceName: {{ .name }}
             servicePort: {{ .port.number }}
        - path: /{{ .name }}/(auth)
          backend:
             serviceName: {{ .name }}
             servicePort: {{ .port.number }}
        - path: /{{ .name }}/(signin)
          backend:
             serviceName: {{ .name }}
             servicePort: {{ .port.number }}
        - path: /{{ .name }}/(signup)
          backend:
             serviceName: {{ .name }}
             servicePort: {{ .port.number }}
        - path: /{{ .name }}/(signout)
          backend:
             serviceName: {{ .name }}
             servicePort: {{ .port.number }}
        - path: /{{ .name }}/(sessions)
          backend:
             serviceName: {{ .name }}
             servicePort: {{ .port.number }}
{{- end}}