apiVersion: v1
kind: Pod
metadata:
{{- with .Values.notificationProcessor }}
   name: {{ .name }}-pod
   labels:
      app: {{ .name }}
spec:
   containers:
   - name: {{ .name }}-container
     image: {{ .image }}
{{- end }}