apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
   name: {{ .Values.paymentEndpoint.label }}-ingress-private
   annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/auth-url: "http://{{ .Values.authEndpoint.service.name }}.{{ .Values.common.namespace }}.svc.cluster.local:{{ .Values.authEndpoint.port.number }}/auth"
      nginx.ingress.kubernetes.io/auth-signin: "http://$host/{{ .Values.authEndpoint.service.name }}/signin"
      nginx.ingress.kubernetes.io/auth-response-headers: "X-User-Id"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
   rules:
   - host: {{ .Values.common.host }}
     http:
{{- with .Values.paymentEndpoint.service }}
        paths:
        - path: /{{ .name }}/(user-account)
          backend:
             serviceName: {{ .name }}
             servicePort: {{ .port.number }}
        - path: /{{ .name }}/(user-transactions)
          backend:
             serviceName: {{ .name }}
             servicePort: {{ .port.number }}             
        - path: /{{ .name }}/(deposit-amount)
          backend:
             serviceName: {{ .name }}
             servicePort: {{ .port.number }}
{{- end }}