apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
   name: {{ .Values.sessionEndpoint.label }}-ingress
   annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
   rules:
   - host: {{ .Values.common.host }}
     http:
{{- with .Values.sessionEndpoint.service }}
        paths:
        - path: /{{ .name }}/(health)
          backend:
             serviceName: {{ .name }}
             servicePort: {{ .port.number }}
{{- end }}