apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
   name: {{ .Values.userEndpoint.label }}-ingress-public
   annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
   rules:
   - host: {{ .Values.common.host }}
     http:
{{- with .Values.userEndpoint.service }}
        paths:
        - path: /{{ .name }}/(health)
          backend:
             serviceName: {{ .name }}
             servicePort: {{ .port.number }}
{{- end }}