apiVersion: v1
kind: Secret
metadata:
   name: db-secret
type: Opaque
data:
   DBPASSWORD: "MHR1UzFAYiQ="
   DBURI: "U2VydmVyPWRiLXNlcnZpY2UsMTAwMDA7SW5pdGlhbCBDYXRhbG9nPU90dXNMYWJzO1VzZXIgSUQ9c2E7UGFzc3dvcmQ9MHR1UzFAYiQ="