apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: app-rs
spec:
   replicas: 3
   selector:
      matchLabels:
         app: app
   template:
      metadata:
         labels:
            app: app
      spec:
         containers:
         - name: app-cnt
           image: gennadytiunov/docker-lab:v2
           ports:
           - containerPort: 8000