apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
  - image: gennadytiunov/kuber-lab:v2
    context: kuber-lab
deploy:
  kubectl:
    manifests:
    - deployment.yaml
    - service.yaml