apiVersion: batch/v1
kind: Job
metadata:
   name: kafka-topic-describer
spec:
   backoffLimit: 1
   template:
      metadata:
         name: kafka-topic-describer
      spec:
         restartPolicy: Never
         containers:
         - name:  kafka-topic-describer
           image: confluentinc/cp-kafka:5.0.1
           command:
           - sh
           - "-c"
           - |
              kafka-topics --describe --zookeeper cp-cp-zookeeper-headless.kafka.svc.cluster.local:2181 --topic users
              kafka-topics --describe --zookeeper cp-cp-zookeeper-headless.kafka.svc.cluster.local:2181 --topic bookings
              kafka-topics --describe --zookeeper cp-cp-zookeeper-headless.kafka.svc.cluster.local:2181 --topic payments
              kafka-topics --describe --zookeeper cp-cp-zookeeper-headless.kafka.svc.cluster.local:2181 --topic payments-replies
              kafka-topics --describe --zookeeper cp-cp-zookeeper-headless.kafka.svc.cluster.local:2181 --topic notifications