{
 "title": "OtusLab (Service, Aggregated)",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "RPS (All Instances, By Action /  Response Code)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (action, code) (rate(http_requests_received_total[1m]))\n"
    }
   ]
  },
  {
   "title": "Latency (99 pctl, seconds) - All Instances, By Action / Response Code",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (action, code, le) (rate(http_request_duration_seconds_bucket[1m])))"
    }
   ]
  },
  {
   "title": "RPS (By Action / Instance)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, action) (rate(http_requests_received_total[1m]))\r"
    }
   ]
  },
  {
   "title": "Latency (99 pctl, seconds) - By Action / Instance",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (instance, action, le) (rate(http_request_duration_seconds_bucket[1m])))"
    }
   ]
  }
 ]
}