{
 "title": "OtusLab (Service API Methods)",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Health - RPC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (action) (rate(http_requests_received_total{action='Health'}[1m]))\r",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (action,code) (rate(http_requests_received_total{action='Health'}[1m]))\r",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "GetAllProducts - RPC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (action) (rate(http_requests_received_total{action='GetAllProducts'}[1m]))\r",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (action,code) (rate(http_requests_received_total{action='GetAllProducts'}[1m]))\r",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Health - Latency (seconds)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by (action, le) (rate(http_request_duration_seconds_bucket{action='Health'}[1m])))",
     "legendFormat": "Max"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (action, le) (rate(http_request_duration_seconds_bucket{action='Health'}[1m])))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (action, le) (rate(http_request_duration_seconds_bucket{action='Health'}[1m])))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (action, le) (rate(http_request_duration_seconds_bucket{action='Health'}[1m])))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "GetAllProducts - Latency (seconds)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by (action, le) (rate(http_request_duration_seconds_bucket{action='GetAllProducts'}[1m])))",
     "legendFormat": "Max"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (action, le) (rate(http_request_duration_seconds_bucket{action='GetAllProducts'}[1m])))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (action, le) (rate(http_request_duration_seconds_bucket{action='GetAllProducts'}[1m])))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (action, le) (rate(http_request_duration_seconds_bucket{action='GetAllProducts'}[1m])))",
     "legendFormat": "Median"
    }
   ]
  }
 ]
}