apiVersion: v1
kind: Service
metadata:
   namespace: {{ .Values.common.namespace }}
   name: {{ .Values.db.service.name }}
spec:
   selector:
      app: {{ .Values.db.label }}
   type: {{ .Values.db.service.type }}
   ports:
   - protocol: {{ .Values.db.service.port.protocol }}
     port: {{ .Values.db.service.port.number }}
     targetPort: {{ .Values.db.port.name }}