{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: {{ .Values.common.namespace }}
  name: {{ .Values.productsApp.service.name }}-monitor
spec:
  namespaceSelector:
    matchNames:
    - {{ .Values.common.namespace }}
  selector:
    matchLabels:
      app: {{ .Values.productsApp.service.name }}
  endpoints:
  - interval: {{ .Values.metrics.serviceMonitor.interval }}
    port: {{ .Values.productsApp.port.name }}
    path: {{ .Values.metrics.serviceMonitor.endpoint }}
{{- end }} 