apiVersion: apps/v1
kind: Deployment
metadata:
   name: app-deployment
spec:
   replicas: 3
   selector:
      matchLabels:
         app: app
   template:
      metadata:
         labels:
            app: app
      spec:
         initContainers:
         - name: db-service-awaiter
           image: busybox:1.28
           command: [
                       "sh",
                       "-c",
                       "until nslookup db-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for db-service; sleep 2; done"
                     ]
         containers:
         - name: app-cnt
           image: gennadytiunov/kuber-lab:v20
           ports:
           - name: app-port
             containerPort: 8000
           env:
              - name: DB_URI
                valueFrom:
                   secretKeyRef:
                      name: db-secret
                      key: DBURI
           livenessProbe:
              httpGet:
                 port: 8000
                 path: /
              initialDelaySeconds: 10
              periodSeconds: 5
              timeoutSeconds: 3
           readinessProbe:
              httpGet:
                 port: 8000
                 path: /health
              initialDelaySeconds: 10
              periodSeconds: 5
              timeoutSeconds: 3