apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
   name: {{ .Values.userEndpoint.label }}-ingress
   annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
   rules:
   - host: {{ .Values.common.host }}
     http:
{{- with .Values.userEndpoint }}     
        paths:
        - path: /{{ .label }}/(.*)
          backend:
             serviceName: {{ .service.name }}
             servicePort: {{ .service.port.number }}
{{- end }}