apiVersion: networking.k8s.io/v1beta1
kind: Ingress
{{- with .Values.app }}
metadata:
   name: app-ingress
   annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
   rules:
   - host: {{ .host }}
     http:
        paths:
        - path: /{{ .virtualPath }}($|/)(.*)
          backend:
             serviceName: {{ .service.name }}
             servicePort: {{ .service.port.number }}
{{- end }}