apiVersion: v1
kind: Secret
metadata:
   name: {{ .Values.db.secret }}
type: Opaque
data:
   DBPASSWORD: {{ index .Values "mssql-linux" "sapassword" | b64enc | quote }}
   DBURI: {{ printf "Server=%s;Initial Catalog=%s;User ID=%s;Password=%s" (include "dbservice.fullname" . ) .Values.db.name .Values.db.user  (index .Values "mssql-linux" "sapassword") | b64enc | quote }}