apiVersion: apps/v1
kind: Deployment
metadata:
    name: hc-deployment
spec:
    replicas: 3
    selector:
       matchLabels:
          app: health-checker
          version: v1
    template:
       metadata:
          labels:
             app: health-checker
             version: v1
       spec:
          containers:
          - name: hc-container
            image: gennadytiunov/kuber-lab:v7
            ports:
              - name: web
                containerPort: 8000
            livenessProbe:
              httpGet:
                port: 8000
                path: /
              initialDelaySeconds: 10
              periodSeconds: 5
              timeoutSeconds: 3
            readinessProbe:
              httpGet:
                port: 8000
                path: /health
              initialDelaySeconds: 10
              periodSeconds: 5
              timeoutSeconds: 3