apiVersion: v1
kind: Service
metadata:
  name: hc-service
spec:
  selector:
    app: health-checker
    version: v1
  ports:
    - protocol: TCP
      port: 9000
      targetPort: web
  type: NodePort